# docker-compose.yml
# Created by: Michael Cole
# Updated by: Michael Cole
# ------------------------
# Instructions for docker-compose on how
# to build the project.
# Run `docker-compose up --build`

version: '3'

services:

    app:
        container_name: app
        build:
            context: ./marbles
            dockerfile: dockerfile
        env_file:
            - ./marbles.env
        ports:
            - "80:80"

