# dockerfile
# Created by: Michael Cole
# Updated by: Michael Cole
# ------------------------
# Build instructions for the app
# container.

FROM python:3.7.5-slim

LABEL maintainer="Michael Cole <mcole042891@gmail.com>"

ENV WORKDIR="/marbles"
RUN mkdir ${WORKDIR}
WORKDIR ${WORKDIR}

RUN apt update; apt install npm -y
RUN npm install bootstrap --save

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . ${WORKDIR}

EXPOSE 5000

CMD flask run --host=${FLASK_HOST} --port=${FLASK_PORT}
