# dockerfile
# Created by: Michael Cole
# Updated by: Michael Cole
# ------------------------
# Build instructions for the nginx
# container - to be used in production

FROM nginx:1.17-alpine

LABEL maintainer="Michael Cole <mcole042891@gmail.com>"

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
